---
title: "Demo of YAML options"
subtitle: With [**palmerpenguins**](https://allisonhorst.github.io/palmerpenguins/index.html)
output: 
  html_document:
    theme: flatly
    code_download: true
    code_folding: hide
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    highlight: espresso
params: 
  species: Gentoo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r libraries, echo = FALSE}
# load libraries
library(tidyverse)
library(palmerpenguins)
```

# The data

```{r}
penguins
```


# Plots 

## Penguin bill dimensions

```{r penguins-plot}
penguins %>%
  ggplot(aes(
    x = bill_length_mm,
    y = bill_depth_mm,
    group = species
  )
  ) +
  geom_point(aes(
    color = species,
    shape = species
  ),
  size = 3,
  alpha = 0.8
  ) +
  geom_smooth(method = "lm", se = FALSE, aes(color = species)) +
  theme_minimal() +
  scale_color_manual(values = c("darkorange", "purple", "cyan4")) +
  labs(
    title = "Penguin bill dimensions",
    subtitle = "Bill length and depth for Adelie, Chinstrap and Gentoo Penguins at Palmer Station LTER",
    x = "Bill length (mm)",
    y = "Bill depth (mm)",
    color = "Penguin species",
    shape = "Penguin species"
  ) +
  theme(
    legend.position = c(0.85, 0.15),
    legend.background = element_rect(fill = "white", color = NA),
    plot.title.position = "plot",
    plot.caption = element_text(hjust = 0, face = "italic"),
    plot.caption.position = "plot"
  )
```

## Histogram of body mass for `r params$species` penguins

```{r}
penguins %>%
  filter(species == params$species) %>%
  ggplot(aes(x = body_mass_g)) +
  geom_histogram(
    alpha = 0.5,
    position = "identity"
  ) +
  scale_fill_manual(values = c("darkorange", "purple", "cyan4")) +
  theme_minimal() +
  labs(
    x = "Body mass (g)",
    y = "Frequency",
    title = glue::glue("{params$species} body mass")
  )
```

# Resources 

- [Bootswatch themes](https://bootswatch.com/3/)

- [Section 3.1](https://bookdown.org/yihui/rmarkdown/html-document.html) of R Markdown:The Definitive Guide

- [Section 17.4](https://bookdown.org/yihui/rmarkdown-cookbook/parameterized-reports.html) of R Markdown Cookbook on parameterized reports